"""
Monitoring daemon that watches SLURM jobs and regenerates W&B reports.

Polls for active W&B runs in a project, regenerates reports when new
data is available, commits and pushes to a cc-reports branch.

Usage:
    # Run in foreground (Ctrl+C to stop)
    uv run python scripts/report_monitor.py --project act-prm-cc

    # Run with custom interval
    uv run python scripts/report_monitor.py --project act-prm-cc --interval 120

    # Single pass (no loop)
    uv run python scripts/report_monitor.py --project act-prm-cc --once
"""
from __future__ import annotations

import argparse
import logging
import os
import signal
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import wandb

sys.path.insert(0, str(Path(__file__).parent))
from wandb_report import generate_report, short_run_name  # noqa: E402

logger = logging.getLogger(__name__)

# Track last known step count per run to avoid redundant regeneration
_last_steps: dict[str, int] = {}
_shutdown = False

REPORTS_BRANCH = "cc-reports"


def _handle_signal(signum, frame):
    global _shutdown
    logger.info("Received signal %d, shutting down...", signum)
    _shutdown = True


def _git(*args: str, env: dict | None = None) -> tuple[int, str]:
    """Run a git command, return (returncode, output)."""
    result = subprocess.run(
        ["git"] + list(args),
        capture_output=True, text=True, timeout=30, env=env,
    )
    return result.returncode, (result.stdout + result.stderr).strip()


def ensure_reports_branch():
    """Ensure cc-reports branch exists remotely."""
    rc, out = _git("ls-remote", "--heads", "origin", REPORTS_BRANCH)
    if REPORTS_BRANCH not in out:
        # Create branch from current HEAD
        _git("branch", REPORTS_BRANCH)
        _git("push", "-u", "origin", REPORTS_BRANCH)
        logger.info("Created branch %s", REPORTS_BRANCH)


def push_reports(reports_dir: Path, project: str):
    """Commit and push changed reports directly to cc-reports ref.

    Uses a temporary git index so commits go only to cc-reports,
    without touching the current working branch.
    """
    rc, status = _git("status", "--porcelain", "--", str(reports_dir))
    if not status.strip():
        return  # Nothing to commit

    with tempfile.NamedTemporaryFile(suffix=".idx", delete=False) as f:
        tmp_index = f.name

    try:
        env = {**os.environ, "GIT_INDEX_FILE": tmp_index}

        # Read existing cc-reports tree if it exists
        rc, parent = _git("rev-parse", "--verify", REPORTS_BRANCH)
        if rc == 0:
            _git("read-tree", REPORTS_BRANCH, env=env)

        # Add reports to temporary index
        _git("add", "--", str(reports_dir), env=env)

        # Write tree and create commit on cc-reports only
        rc, tree = _git("write-tree", env=env)
        if rc != 0:
            logger.error("write-tree failed: %s", tree)
            return

        parent_args = ["-p", parent] if parent else []
        rc, commit = _git(
            "commit-tree", tree, *parent_args,
            "-m", f"Update {project} reports\n\nAuto-generated by report_monitor",
            env=env,
        )
        if rc != 0:
            logger.error("commit-tree failed: %s", commit)
            return

        # Update cc-reports ref and push
        _git("update-ref", f"refs/heads/{REPORTS_BRANCH}", commit)
        rc, out = _git("push", "origin", REPORTS_BRANCH)
        if rc != 0:
            logger.error("Push failed: %s", out)
            rc, out = _git("push", "--force-with-lease", "origin", REPORTS_BRANCH)
            if rc != 0:
                logger.error("Force push also failed: %s", out)
        else:
            logger.info("Pushed reports to origin/%s", REPORTS_BRANCH)
    finally:
        os.unlink(tmp_index)


def get_max_step(run: wandb.apis.public.Run) -> int:
    """Get the latest step from run summary without fetching full history."""
    summary = run.summary
    return summary.get("_step", 0)


def monitor_pass(
    api: wandb.Api,
    entity: str,
    project: str,
    reports_dir: Path,
) -> int:
    """Single monitoring pass. Returns number of reports updated."""
    runs = api.runs(
        f"{entity}/{project}",
        filters={"state": {"$in": ["running", "finished", "crashed"]}},
    )

    updated = 0
    for run in runs:
        name = short_run_name(run)
        current_step = get_max_step(run)
        last_step = _last_steps.get(run.id, -1)

        if current_step <= last_step:
            continue

        status = "NEW" if last_step == -1 else f"step {last_step}→{current_step}"
        logger.info("[%s] %s (%s, %s)", name, run.state, status, run.id[:8])

        try:
            generate_report(run, reports_dir, entity)
            _last_steps[run.id] = current_step
            updated += 1
        except Exception as e:
            logger.error("[%s] Report failed: %s", name, e)

    return updated


def main():
    parser = argparse.ArgumentParser(description="Monitor W&B runs and generate reports")
    parser.add_argument("--project", required=True, help="W&B project name")
    parser.add_argument("--entity", default="hazy-research", help="W&B entity")
    parser.add_argument("--reports-dir", default="./reports", help="Output directory")
    parser.add_argument("--interval", type=int, default=60, help="Seconds between polls")
    parser.add_argument("--once", action="store_true", help="Single pass, then exit")
    parser.add_argument("--no-push", action="store_true", help="Skip git push")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(message)s",
        datefmt="%H:%M:%S",
    )

    reports_dir = Path(args.reports_dir) / args.project
    reports_dir.mkdir(parents=True, exist_ok=True)
    api = wandb.Api()

    if not args.no_push:
        ensure_reports_branch()

    if args.once:
        n = monitor_pass(api, args.entity, args.project, reports_dir)
        if n > 0 and not args.no_push:
            push_reports(Path(args.reports_dir), args.project)
        logger.info("Updated %d reports", n)
        return

    # Daemon loop
    signal.signal(signal.SIGINT, _handle_signal)
    signal.signal(signal.SIGTERM, _handle_signal)

    logger.info("Monitoring %s/%s every %ds (reports → %s, push → origin/%s)",
                args.entity, args.project, args.interval, reports_dir, REPORTS_BRANCH)

    while not _shutdown:
        try:
            n = monitor_pass(api, args.entity, args.project, reports_dir)
            if n > 0:
                logger.info("Updated %d reports", n)
                if not args.no_push:
                    push_reports(Path(args.reports_dir), args.project)
            else:
                logger.info("No updates")
        except Exception as e:
            logger.error("Monitor pass failed: %s", e)

        # Interruptible sleep
        for _ in range(args.interval):
            if _shutdown:
                break
            time.sleep(1)

    logger.info("Monitor stopped")


if __name__ == "__main__":
    main()
